'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class barangdagangan
    Public Property id_barang As String
    Public Property id_penjual As String
    Public Property image As String
    Public Property nama_barang As String
    Public Property deskripsi As String
    Public Property harga As Nullable(Of Long)
    Public Property tanggal_upload As Date
    Public Property deleted As Integer

    Public Overridable Property user As user
    Public Overridable Property carts As ICollection(Of cart) = New HashSet(Of cart)

End Class
