'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cart
    Public Property id As Long
    Public Property id_barang As String
    Public Property id_pembeli As String
    Public Property jumlah As Nullable(Of Integer)
    Public Property status As Integer
    Public Property id_transaksi As String
    Public Property resi As String

    Public Overridable Property barangdagangan As barangdagangan
    Public Overridable Property user As user

End Class
