'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class OnlineShopEntity
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OnlineShopEntity")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property barangdagangans() As DbSet(Of barangdagangan)
    Public Overridable Property carts() As DbSet(Of cart)
    Public Overridable Property transactions() As DbSet(Of transaction)
    Public Overridable Property users() As DbSet(Of user)

End Class
